#!/usr/bin/env python3
"""
Paper sweep — Open-Ended HYBRID SWA-DPBR — Logit-Noise Robustness Study
=======================================================================
Kaggle OFFLINE version — no Internet, no git clone, no pip install.

Goal
----
Quantify how each method (vanilla, RAW SWA-DPBR, SAFE blend, ORACLE_C,
ORACLE_D, HYBRID) degrades under additive Gaussian noise on the actor's
A/B-token logit gap. This complements the noiseless table
(``tab:safe_swa_results``) with a robustness curve suitable for the
paper's "Sensitivity / Stability" section.

Setup
-----
For each scenario s and persona p, the noiseless judge delta δ̂_{s,p} is
already cached in ``combined/{country}.jsonl`` from a prior noiseless
run. The robustness pipeline only re-runs the **downstream** stages
(DPBR + safe-blend + oracle + hybrid) on perturbed inputs:

    δ_{s,p}(σ, seed) = δ̂_{s,p}  +  η_{s,p}     η_{s,p} ~ iid N(0, σ²)

where η is generated by a PRNG seeded reproducibly per
(noise_seed, country) so:

  - Same (σ, seed) → identical noisy deltas → bit-reproducible MIS.
  - Different seeds → independent draws → Monte-Carlo error bars.
  - Different countries under the same seed are decorrelated.

We sweep σ across multiple magnitudes relative to the empirical δ scale
(|δ| ≈ 5–10 from the actor self-test) and average MIS across multiple
seeds at every σ > 0:

    SIGMA_GRID = [0.0, 0.25, 0.5, 1.0, 2.0]
    SEEDS      = [42, 123, 456]

σ = 0 is the noiseless baseline (single deterministic run; multiple
seeds would give identical results). σ > 0 produces 3 seeded runs each
so the per-method curve has mean ± std error bars.

Compute budget
--------------
* 1 baseline run (σ=0): full pipeline including model load + actor
  generation. ≈3–5h on Kaggle RTX 6000 96GB for 20 countries × 500
  scenarios × 5 personas. Populates the shared combined/ cache.
* 12 noise runs (σ ∈ {0.25, 0.5, 1.0, 2.0} × seeds {42, 123, 456}):
  ``skip_model_load=True``, ``combined_dir_override`` points to the
  baseline's combined/. Each run reuses cached deltas, only re-runs
  DPBR + AMCE + safe-blend + hybrid. ≈10–20 min per run = ~3–4 h total.

Total ≈ 7–9 h, comfortably under the 12h Kaggle limit.

Outputs
-------
Each (σ, seed) writes to a dedicated subdirectory under
``results/openended_robust/``::

    results/openended_robust/
    ├── combined/                          (shared cache, one set of clean deltas)
    │   ├── USA.jsonl, USA.csv
    │   └── ...
    ├── sigma_0.00_seed_42/                (baseline)
    │   ├── safe/{country}/...
    │   └── compare/comparison_wide.csv
    ├── sigma_0.25_seed_42/
    ├── sigma_0.25_seed_123/
    ├── ...
    └── compare_robust/                    (aggregated)
        ├── robustness_full.csv            (long: every (sigma, seed, country, method))
        ├── robustness_per_country.csv     (mean±std MIS per country per (method, sigma))
        ├── robustness_aggregate.csv       (mean±std MIS per (method, sigma) across countries+seeds)
        └── robustness_summary.txt         (paper-ready ASCII table)

The paper's robustness figure / table can be drawn directly from
``robustness_aggregate.csv``.

Configuration
-------------
Edit the RUN CONFIG block near the top of this file. Set
``RUN_BATCH="b1"`` to start with 10 countries if running for the first
time on a tight session.

Usage
-----
    !python /kaggle/input/cultural-alignment/exp_paper/exp_paper_openended_robust.py
"""

from __future__ import annotations

import gc
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Dict, List, Tuple

# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║  1. KAGGLE OFFLINE BOOTSTRAP                                                ║
# ╚══════════════════════════════════════════════════════════════════════════════╝

PROJECT_DATASET_DIR = "/kaggle/input/notebooks/foundnotkiet/git-moral/cultural-alignment"
PROJECT_DATASET_DIR_ALT = "/kaggle/input/notebooks/foundnotkiet/git-moral/cultural_alignment"
ACTOR_MODEL_LOCAL_PATH = "/kaggle/input/models/qwen-lm/qwen2.5/transformers/7b-instruct/1"
MULTITP_DATA_PATH = "/kaggle/input/datasets/trungkiet/mutltitp-data/data/data"
WVS_DATA_PATH = "/kaggle/input/datasets/trungkiet/mutltitp-data/WVS_Cross-National_Wave_7_inverted_csv_v6_0.csv"
HUMAN_AMCE_PATH = "/kaggle/input/datasets/trungkiet/mutltitp-data/data/data/country_specific_ACME.csv"
WORK_DIR = "/kaggle/working/cultural_alignment"

os.environ["TORCHDYNAMO_DISABLE"] = "1"
os.environ["TORCH_COMPILE_DISABLE"] = "1"
os.environ["UNSLOTH_DISABLE_STATISTICS"] = "1"
os.environ["UNSLOTH_DISABLE_AUTO_COMPILE"] = "1"
os.environ["PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION"] = "python"
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"
os.environ["HF_HUB_OFFLINE"] = "1"
os.environ["TRANSFORMERS_OFFLINE"] = "1"
os.environ.setdefault("MORAL_MODEL_BACKEND", "hf_native")
os.environ.setdefault("EXP24_ESS_ANCHOR_REG", "1")

# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║  RUN CONFIG — edit here, no env vars needed.                                ║
# ╚══════════════════════════════════════════════════════════════════════════════╝
RUN_BATCH: str = "all"             # "b1" (1-10) | "b2" (11-20) | "all"
RUN_N_SCENARIOS: int = 500
RUN_MAX_NEW_TOKENS_ACTOR: int = 8
LOAD_4BIT: bool = False

# ── Robustness sweep grid ────────────────────────────────────────────────────
# σ values are absolute logit-units. Empirical |δ| from actor_logit_delta on
# Qwen2.5-7B is roughly 3–10 across the 20 paper countries (see
# tracker_open_ended.md), so σ=1 ≈ 10–30% of the typical signal magnitude
# and σ=2 stress-tests the high-noise regime where vanilla starts to fail.
SIGMA_GRID: Tuple[float, ...] = (0.0, 0.25, 0.5, 1.0, 2.0)
SEEDS: Tuple[int, ...] = (42, 123, 456)

# SafeBlend hyperparameters — same as exp_paper_openended_safe / hybrid.
ALPHA_MAX: float = 0.30
DPBR_R_MIN: float = 0.85
MIN_VANILLA_CONF: float = 0.5
MAGNITUDE_RATIO_MAX: float = 2.5
BLEND_FLOOR: float = 0.5
PERSONA_STD_MAX: float = 3.0
COUNTRY_MIN_ALPHA: float = 0.05

os.environ["EXP24_VAR_SCALE"] = "0.04"


def _on_kaggle() -> bool:
    return os.path.isdir("/kaggle/working")


def _setup_project() -> str:
    if _on_kaggle():
        project_src = None
        for cand in (PROJECT_DATASET_DIR, PROJECT_DATASET_DIR_ALT):
            if os.path.isdir(cand):
                project_src = cand
                break
        if os.path.isdir(WORK_DIR) and os.path.isfile(
            os.path.join(WORK_DIR, "src", "controller.py")
        ):
            print(f"[SETUP] Working dir exists: {WORK_DIR}")
        else:
            if project_src is None:
                raise RuntimeError(
                    "Project dataset not found. Checked: "
                    f"{PROJECT_DATASET_DIR} and {PROJECT_DATASET_DIR_ALT}"
                )
            print(f"[SETUP] Copying project from {project_src} → {WORK_DIR} ...")
            shutil.copytree(project_src, WORK_DIR, dirs_exist_ok=True)
        os.chdir(WORK_DIR)
        sys.path.insert(0, WORK_DIR)
        return WORK_DIR
    else:
        here = os.getcwd()
        if os.path.isfile(os.path.join(here, "src", "controller.py")):
            sys.path.insert(0, here)
            return here
        raise RuntimeError("Not on Kaggle and not inside repo root.")


def _resolve_model_path(base_path: str, label: str) -> str:
    if not _on_kaggle():
        return os.environ.get(f"{label}_MODEL_PATH", base_path)
    if os.path.isdir(base_path) and os.path.isfile(os.path.join(base_path, "config.json")):
        return base_path
    for sub in Path(base_path).rglob("config.json"):
        return str(sub.parent)
    candidates = [
        f"{base_path}/transformers/default/1",
        f"{base_path}/pytorch/default/1",
    ]
    for c in candidates:
        if os.path.isdir(c) and os.path.isfile(os.path.join(c, "config.json")):
            return c
    raise RuntimeError(f"{label} model weights not found at {base_path}")


# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║  2. BOOTSTRAP                                                              ║
# ╚══════════════════════════════════════════════════════════════════════════════╝

print("=" * 70)
print("  KAGGLE OFFLINE — Open-Ended ROBUSTNESS sweep (Gaussian logit noise)")
print(f"  σ ∈ {list(SIGMA_GRID)}   seeds ∈ {list(SEEDS)}")
print("=" * 70)

_setup_project()

ACTOR_MODEL_PATH = _resolve_model_path(ACTOR_MODEL_LOCAL_PATH, "ACTOR")
print(f"[SETUP] Actor + self-judge model path: {ACTOR_MODEL_PATH}")

if _on_kaggle():
    subprocess.run(
        "pip install -q --no-deps --no-index scipy tqdm sentencepiece protobuf "
        "2>/dev/null || true",
        shell=True, check=False,
    )

# Late imports — must come AFTER _setup_project so sys.path is set up.
import numpy as np  # noqa: E402
import pandas as pd  # noqa: E402

from exp_paper.openended.unified_actor_judge_safe import (  # noqa: E402
    SafeUnifiedConfig, run_unified_safe,
)
from exp_paper.paper_countries import PAPER_20_COUNTRIES  # noqa: E402


_PAPER_20: List[str] = list(PAPER_20_COUNTRIES)
_BATCHES: Dict[str, List[str]] = {
    "all": _PAPER_20,
    "b1": _PAPER_20[:10],
    "b2": _PAPER_20[10:],
}


# ----------------------------------------------------------------------------
# Helpers — sweep configuration + aggregation
# ----------------------------------------------------------------------------
def _expand_sweep(
    sigma_grid: Tuple[float, ...], seeds: Tuple[int, ...]
) -> List[Tuple[float, int]]:
    """Build the (sigma, seed) list. σ=0 is deterministic so only seed[0] is used."""
    out: List[Tuple[float, int]] = []
    for sigma in sigma_grid:
        if sigma == 0.0:
            out.append((0.0, int(seeds[0])))
        else:
            for s in seeds:
                out.append((float(sigma), int(s)))
    return out


def _run_dir_for(base: Path, sigma: float, seed: int) -> Path:
    return base / f"sigma_{sigma:.2f}_seed_{seed}"


def _collect_robustness(
    base: Path, sweep: List[Tuple[float, int]]
) -> pd.DataFrame:
    """Concatenate every (σ, seed) run's comparison_wide.csv into one frame."""
    frames: List[pd.DataFrame] = []
    for sigma, seed in sweep:
        wide_path = _run_dir_for(base, sigma, seed) / "compare" / "comparison_wide.csv"
        if not wide_path.exists():
            print(f"[WARN] missing wide CSV: {wide_path}")
            continue
        df = pd.read_csv(wide_path)
        df["noise_sigma"] = float(sigma)
        df["noise_seed"] = int(seed)
        frames.append(df)
    if not frames:
        return pd.DataFrame()
    return pd.concat(frames, ignore_index=True)


def _aggregate_per_country(full: pd.DataFrame) -> pd.DataFrame:
    """For each (country, sigma): average MIS across seeds, per method.

    Output columns: country, noise_sigma, {method}_mis_mean, {method}_mis_std,
    {method}_mis_n_seeds  for method ∈ {van, raw, safe, oracle_c, oracle_d, hybrid}.
    """
    if full.empty:
        return pd.DataFrame()
    methods = ("van", "raw", "safe", "oracle_c", "oracle_d", "hybrid")
    rows: List[Dict[str, object]] = []
    for (country, sigma), grp in full.groupby(["country", "noise_sigma"]):
        rec: Dict[str, object] = {
            "country": country, "noise_sigma": float(sigma),
            "n_seeds": int(grp["noise_seed"].nunique()),
        }
        for m in methods:
            col = f"{m}_mis"
            if col in grp.columns:
                vals = grp[col].dropna().to_numpy(dtype=float)
                rec[f"{m}_mis_mean"] = float(np.mean(vals)) if vals.size else float("nan")
                rec[f"{m}_mis_std"] = float(np.std(vals, ddof=1)) if vals.size > 1 else 0.0
                rec[f"{m}_mis_n"] = int(vals.size)
        rows.append(rec)
    out = pd.DataFrame(rows).sort_values(["country", "noise_sigma"]).reset_index(drop=True)
    return out


def _aggregate_overall(full: pd.DataFrame) -> pd.DataFrame:
    """For each (sigma, method): mean MIS over all (country, seed) cells.

    This is the headline "robustness curve" figure in the paper. Output:
      noise_sigma, n_observations, van_mis_mean, van_mis_std, ...
    """
    if full.empty:
        return pd.DataFrame()
    methods = ("van", "raw", "safe", "oracle_c", "oracle_d", "hybrid")
    rows: List[Dict[str, object]] = []
    for sigma, grp in full.groupby("noise_sigma"):
        rec: Dict[str, object] = {
            "noise_sigma": float(sigma),
            "n_countries": int(grp["country"].nunique()),
            "n_seeds": int(grp["noise_seed"].nunique()),
            "n_observations": int(len(grp)),
        }
        for m in methods:
            col = f"{m}_mis"
            if col in grp.columns:
                vals = grp[col].dropna().to_numpy(dtype=float)
                rec[f"{m}_mis_mean"] = float(np.mean(vals)) if vals.size else float("nan")
                rec[f"{m}_mis_std"] = float(np.std(vals, ddof=1)) if vals.size > 1 else 0.0
                # Win rate vs vanilla at this σ (per country×seed cell)
                if m != "van":
                    van_vals = grp[f"van_mis"].to_numpy(dtype=float) \
                        if "van_mis" in grp.columns else None
                    if van_vals is not None and vals.size == van_vals.size:
                        wins = int((vals < van_vals).sum())
                        rec[f"{m}_wins_vs_van"] = wins
                        rec[f"{m}_total_cells"] = int(vals.size)
        rows.append(rec)
    out = pd.DataFrame(rows).sort_values("noise_sigma").reset_index(drop=True)
    return out


def _format_summary_text(agg: pd.DataFrame) -> str:
    """Paper-ready ASCII table — one row per σ, columns are method MIS mean±std."""
    if agg.empty:
        return "(no robustness data)"
    methods = (
        ("van", "VAN"),
        ("raw", "RAW"),
        ("safe", "SAFE"),
        ("oracle_c", "ORC_C"),
        ("oracle_d", "ORC_D"),
        ("hybrid", "HYBRID"),
    )
    lines: List[str] = []
    lines.append("Robustness summary — MIS (mean ± std across countries × seeds)")
    lines.append("-" * 100)
    header = f"{'σ':>6}  {'n_obs':>6}  " + "  ".join(
        f"{lbl:>16}" for _, lbl in methods
    )
    lines.append(header)
    lines.append("-" * 100)
    for _, row in agg.iterrows():
        cells: List[str] = []
        for key, _lbl in methods:
            mean = row.get(f"{key}_mis_mean", float("nan"))
            std = row.get(f"{key}_mis_std", float("nan"))
            cells.append(f"{mean:>7.4f}±{std:>5.4f}")
        lines.append(
            f"{float(row['noise_sigma']):>6.2f}  {int(row['n_observations']):>6d}  "
            + "  ".join(cells)
        )
    return "\n".join(lines)


def _build_noiseless_paper_table(baseline_wide: pd.DataFrame) -> pd.DataFrame:
    """Build paper-ready noiseless table from baseline comparison_wide.csv.

    Output schema mirrors the manuscript table:
      country, van, raw, oracle_d, hybrid, delta_pct, hybrid_source
    where delta_pct = 100 * (van - hybrid) / van.
    """
    if baseline_wide.empty:
        return pd.DataFrame()
    req = {"country", "van_mis", "raw_mis", "oracle_d_mis", "hybrid_mis"}
    if not req.issubset(set(baseline_wide.columns)):
        return pd.DataFrame()
    df = baseline_wide.copy()
    df["delta_pct"] = 100.0 * (df["van_mis"] - df["hybrid_mis"]) / df["van_mis"]
    out = pd.DataFrame({
        "country": df["country"],
        "van": df["van_mis"],
        "raw": df["raw_mis"],
        "oracle_d": df["oracle_d_mis"],
        "hybrid": df["hybrid_mis"],
        "delta_pct": df["delta_pct"],
        "hybrid_source": df.get("hybrid_source", ""),
    })
    # Keep paper country order as emitted by pipeline; append mean row.
    mean_row = {
        "country": "MEAN",
        "van": float(out["van"].mean()),
        "raw": float(out["raw"].mean()),
        "oracle_d": float(out["oracle_d"].mean()),
        "hybrid": float(out["hybrid"].mean()),
        "delta_pct": float(out["delta_pct"].mean()),
        "hybrid_source": "",
    }
    out = pd.concat([out, pd.DataFrame([mean_row])], ignore_index=True)
    return out


def _to_latex_noiseless(tbl: pd.DataFrame) -> str:
    """Render the noiseless main table as a compact LaTeX tabular block."""
    if tbl.empty:
        return "% empty noiseless table\n"
    lines: List[str] = []
    lines.append("\\begin{tabular}{lccccc}")
    lines.append("\\toprule")
    lines.append("Country & VAN & RAW & ORACLE\\_D & HYBRID & $\\Delta\\%$ \\\\")
    lines.append("\\midrule")
    for _, r in tbl.iterrows():
        c = str(r["country"])
        if c == "MEAN":
            lines.append("\\midrule")
            lines.append(
                f"\\textbf{{MEAN}} & \\textbf{{{r['van']:.4f}}} & "
                f"\\textbf{{{r['raw']:.4f}}} & \\textbf{{{r['oracle_d']:.4f}}} & "
                f"\\textbf{{{r['hybrid']:.4f}}} & \\textbf{{{r['delta_pct']:+.2f}\\%}} \\\\"
            )
        else:
            lines.append(
                f"{c} & {r['van']:.4f} & {r['raw']:.4f} & {r['oracle_d']:.4f} & "
                f"\\textbf{{{r['hybrid']:.4f}}} & {r['delta_pct']:+.2f}\\% \\\\"
            )
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    return "\n".join(lines) + "\n"


def _to_latex_robustness(agg: pd.DataFrame) -> str:
    """Render robustness aggregate as LaTeX table (mean±std MIS)."""
    if agg.empty:
        return "% empty robustness table\n"
    methods = ("van", "raw", "safe", "oracle_c", "oracle_d", "hybrid")
    label = {
        "van": "VAN",
        "raw": "RAW",
        "safe": "SAFE",
        "oracle_c": "ORACLE$_C$",
        "oracle_d": "ORACLE$_D$",
        "hybrid": "HYBRID",
    }
    lines: List[str] = []
    lines.append("\\begin{tabular}{c" + "c" * len(methods) + "}")
    lines.append("\\toprule")
    lines.append("$\\sigma$ & " + " & ".join(label[m] for m in methods) + " \\\\")
    lines.append("\\midrule")
    for _, r in agg.iterrows():
        cells: List[str] = []
        for m in methods:
            mu = float(r.get(f"{m}_mis_mean", float("nan")))
            sd = float(r.get(f"{m}_mis_std", float("nan")))
            cells.append(f"{mu:.4f}$\\pm${sd:.4f}")
        lines.append(f"{float(r['noise_sigma']):.2f} & " + " & ".join(cells) + " \\\\")
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    return "\n".join(lines) + "\n"


# ----------------------------------------------------------------------------
# Main
# ----------------------------------------------------------------------------
def _make_cfg(
    countries: List[str], out_dir: Path, combined_dir_override: Path,
    sigma: float, seed: int, skip_model_load: bool,
) -> SafeUnifiedConfig:
    return SafeUnifiedConfig(
        model_name=ACTOR_MODEL_PATH,
        out_dir=str(out_dir),
        multitp_data_path=MULTITP_DATA_PATH,
        wvs_data_path=WVS_DATA_PATH,
        human_amce_path=HUMAN_AMCE_PATH,
        use_real_data=os.path.isdir(MULTITP_DATA_PATH),
        n_scenarios=RUN_N_SCENARIOS,
        max_new_tokens_actor=RUN_MAX_NEW_TOKENS_ACTOR,
        load_in_4bit=LOAD_4BIT,
        countries=countries,
        model_label=f"qwen25_7b_robust_s{sigma:.2f}_k{seed}",
        alpha_max=ALPHA_MAX,
        dpbr_r_min=DPBR_R_MIN,
        min_vanilla_conf=MIN_VANILLA_CONF,
        magnitude_ratio_max=MAGNITUDE_RATIO_MAX,
        blend_floor=BLEND_FLOOR,
        persona_std_max=PERSONA_STD_MAX,
        country_min_alpha=COUNTRY_MIN_ALPHA,
        noise_sigma=float(sigma),
        noise_seed=int(seed),
        combined_dir_override=str(combined_dir_override),
        skip_model_load=skip_model_load,
    )


def main() -> None:
    if RUN_BATCH not in _BATCHES:
        raise ValueError(f"RUN_BATCH must be one of {sorted(_BATCHES)}, got {RUN_BATCH!r}")

    countries = list(_BATCHES[RUN_BATCH])
    base_root = Path(
        f"{WORK_DIR}/results/openended_robust" if _on_kaggle() else
        str(Path(__file__).parent.parent / "results" / "openended_robust")
    )
    base_root.mkdir(parents=True, exist_ok=True)
    shared_combined = base_root / "combined"
    shared_combined.mkdir(parents=True, exist_ok=True)

    sweep = _expand_sweep(SIGMA_GRID, SEEDS)
    print(f"\n[ROBUST] sweep size = {len(sweep)}  countries={countries}")
    for sigma, seed in sweep:
        print(f"    σ={sigma:.2f}  seed={seed}  → {_run_dir_for(base_root, sigma, seed).name}")

    print(f"\n[ROBUST] shared combined cache: {shared_combined}")
    print(f"[ROBUST] base_root: {base_root}")

    # ── Step 1: noiseless baseline ─────────────────────────────────────────
    # Runs full pipeline (model load + actor generation + DPBR + AMCE +
    # safe-blend + hybrid). Populates the shared combined/ cache. All
    # subsequent (σ>0, seed) runs re-use this cache via combined_dir_override.
    sigma0, seed0 = sweep[0]
    assert sigma0 == 0.0, "first sweep entry must be the σ=0 baseline"
    out0 = _run_dir_for(base_root, sigma0, seed0)
    out0.mkdir(parents=True, exist_ok=True)
    print(f"\n{'='*70}\n[ROBUST 1/{len(sweep)}] BASELINE σ=0 seed={seed0}\n{'='*70}")
    cfg0 = _make_cfg(
        countries=countries, out_dir=out0,
        combined_dir_override=shared_combined,
        sigma=sigma0, seed=seed0,
        skip_model_load=False,  # baseline does the heavy generation
    )
    run_unified_safe(cfg0)
    gc.collect()

    # ── Step 2: noise sweep ────────────────────────────────────────────────
    # skip_model_load=True for every σ>0 run. Each run re-applies a fresh
    # noise realization (controlled by SeedSequence in unified_actor_judge_safe)
    # to the cached deltas and re-runs DPBR + AMCE + safe-blend + hybrid only.
    for ix, (sigma, seed) in enumerate(sweep[1:], start=2):
        out_dir = _run_dir_for(base_root, sigma, seed)
        out_dir.mkdir(parents=True, exist_ok=True)
        print(f"\n{'='*70}\n[ROBUST {ix}/{len(sweep)}] σ={sigma:.2f} seed={seed}\n{'='*70}")
        cfg = _make_cfg(
            countries=countries, out_dir=out_dir,
            combined_dir_override=shared_combined,
            sigma=sigma, seed=seed,
            skip_model_load=True,
        )
        run_unified_safe(cfg)
        gc.collect()

    # ── Step 3: aggregate ──────────────────────────────────────────────────
    print(f"\n{'='*70}\n[ROBUST] AGGREGATING — {len(sweep)} runs\n{'='*70}")
    cmp_dir = base_root / "compare_robust"
    cmp_dir.mkdir(parents=True, exist_ok=True)

    full = _collect_robustness(base_root, sweep)
    if full.empty:
        print("[ROBUST] no per-run wide tables found — nothing to aggregate.")
        return
    full_path = cmp_dir / "robustness_full.csv"
    full.to_csv(full_path, index=False)
    print(f"[ROBUST] wrote long-format full table: {full_path}")

    per_country = _aggregate_per_country(full)
    pc_path = cmp_dir / "robustness_per_country.csv"
    per_country.to_csv(pc_path, index=False)
    print(f"[ROBUST] wrote per-country aggregate: {pc_path}")

    overall = _aggregate_overall(full)
    ov_path = cmp_dir / "robustness_aggregate.csv"
    overall.to_csv(ov_path, index=False)
    print(f"[ROBUST] wrote overall aggregate:    {ov_path}")

    summary_text = _format_summary_text(overall)
    summary_path = cmp_dir / "robustness_summary.txt"
    summary_path.write_text(summary_text, encoding="utf-8")
    print(f"[ROBUST] wrote summary table:        {summary_path}")
    print()
    print(summary_text)

    # ── Step 4: paper bundle (one-click NeurIPS artifacts) ────────────────
    # Export (a) main noiseless table and (b) robustness table in CSV + TeX
    # so the user can run this single script and paste outputs directly.
    baseline_wide_path = _run_dir_for(base_root, sigma0, seed0) / "compare" / "comparison_wide.csv"
    if baseline_wide_path.exists():
        baseline_wide = pd.read_csv(baseline_wide_path)
        noiseless_tbl = _build_noiseless_paper_table(baseline_wide)
        if not noiseless_tbl.empty:
            noiseless_csv = cmp_dir / "paper_noiseless_table.csv"
            noiseless_tbl.to_csv(noiseless_csv, index=False)
            noiseless_tex = cmp_dir / "paper_noiseless_table.tex"
            noiseless_tex.write_text(_to_latex_noiseless(noiseless_tbl), encoding="utf-8")
            print(f"[ROBUST] wrote paper noiseless CSV:  {noiseless_csv}")
            print(f"[ROBUST] wrote paper noiseless TeX:  {noiseless_tex}")
    robust_tex = cmp_dir / "paper_robustness_table.tex"
    robust_tex.write_text(_to_latex_robustness(overall), encoding="utf-8")
    print(f"[ROBUST] wrote paper robust TeX:     {robust_tex}")

    # Persist the sweep + hyperparameters + grid to a sidecar JSON for
    # reproducibility traceability in the paper appendix.
    meta = {
        "sigma_grid": list(SIGMA_GRID),
        "seeds": list(SEEDS),
        "n_scenarios": RUN_N_SCENARIOS,
        "run_batch": RUN_BATCH,
        "countries": countries,
        "model": ACTOR_MODEL_PATH,
        "alpha_max": ALPHA_MAX,
        "dpbr_r_min": DPBR_R_MIN,
        "min_vanilla_conf": MIN_VANILLA_CONF,
        "magnitude_ratio_max": MAGNITUDE_RATIO_MAX,
        "blend_floor": BLEND_FLOOR,
        "persona_std_max": PERSONA_STD_MAX,
        "country_min_alpha": COUNTRY_MIN_ALPHA,
        "exp24_var_scale": os.environ.get("EXP24_VAR_SCALE", ""),
        "noise_model": "additive Gaussian on judge δ (logit gap)",
        "noise_seeding": (
            "np.random.SeedSequence([noise_seed, hash(country) & 0xFFFFFFFF]); "
            "iid draws applied to vanilla and 4 persona deltas per scenario"
        ),
    }
    (cmp_dir / "robustness_meta.json").write_text(
        json.dumps(meta, ensure_ascii=False, indent=2), encoding="utf-8",
    )
    print(f"[ROBUST] wrote sidecar meta:         {cmp_dir/'robustness_meta.json'}")


if __name__ == "__main__":
    main()
