"""SAFE open-ended SWA-DPBR — guaranteed-not-worse-than-vanilla variant.

Three architectural fixes vs :mod:`exp_paper.openended.unified_actor_judge`,
each addressing a root cause identified in tracker_open_ended.md cross-scale
analysis:

  1. **Continuous-δ from judge logits** (fixes signal-bottleneck cause):
     instead of generating judge text and parsing it through the
     ``{A, B, UNCERTAIN}`` bottleneck (3-5 quantized values), we forward the
     judge ONE step on a "decisive" closing prompt and read the next-token
     logits at the A/B token positions. δ = logit(B) − logit(A) is real-valued,
     restoring the smooth signal regime PT-IS was designed for.

  2. **Per-scenario vanilla-anchored bounded blend** (fixes over-correction
     cause): after DPBR produces δ_swa, blend with vanilla as
     ``δ_final = (1−α)·δ_van + α·δ_swa`` with ``α ∈ [0, 0.30]`` and four hard
     safety gates (sign agreement on confident vanilla, DPBR reliability,
     magnitude bound, persona consensus). When ANY gate fails, α=0 and the
     scenario falls back to vanilla — identical output to the vanilla baseline.

  3. **Country-level abstain** (fixes catastrophic-country tail risk):
     if mean α across a country's scenarios is below ``country_min_alpha``,
     the SWA correction had no real leverage and the country reports
     vanilla output verbatim.

These three layers form a safety net: layer 1 enables signal-faithful SWA;
layer 2 caps SWA's per-scenario blast radius; layer 3 catches countries where
SWA still drifts net-negative after layer 2. By construction, on scenarios
where any gate fails the output IS the vanilla output — so the safe pipeline
cannot do worse than vanilla in expectation, modulo the (small) noise on
scenarios where all gates pass.

Reuses helper functions from :mod:`exp_paper.openended.unified_actor_judge`
where the schemas / prompts are identical (scenario loading, persona texts,
JSONL I/O, actor generation).
"""

from __future__ import annotations

import csv
import gc
import json
import math
import os
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional, Set, Tuple

import numpy as np
import pandas as pd
import torch

from src.amce import (
    compute_alignment_metrics,
    compute_amce_from_preferences,
    compute_per_dimension_alignment,
    load_human_amce,
)
from src.constants import COUNTRY_LANG
from src.judge_logits import actor_logit_delta, resolve_ab_token_ids
from src.model import ChatTemplateHelper, load_model_hf_native, setup_seeds
from src.openended_prompts import build_openended_prompt
from src.personas import SUPPORTED_COUNTRIES
from src.pseudo_delta import T_DECISION, pseudo_p_right_from_delta
from src.safe_blend import (
    SafeBlendConfig,
    country_level_decision,
    safe_blend_scalar,
)

from exp_paper.openended.dpbr_offline import Exp24DualPassControllerOffline
from exp_paper.openended.unified_actor_judge import (
    AGENT_ROLES,
    _build_persona_texts,
    _load_combined_rows,
    _load_scenarios_bilingual,
    _read_existing_keys,
    _summarize,
)


SCHEMA_VERSION_SAFE: int = 4  # v4: judge_delta is now actor_logit_delta (was judge_logit_delta in v3)


@dataclass
class SafeUnifiedConfig:
    """Config for the SAFE open-ended pipeline.

    Mirrors :class:`UnifiedConfig` plus :class:`SafeBlendConfig` knobs.
    """
    model_name: str = "Qwen/Qwen2.5-7B-Instruct"
    out_dir: str = "/kaggle/working/cultural_alignment/results/openended_safe"
    multitp_data_path: str = ""
    wvs_data_path: str = ""
    human_amce_path: str = ""
    use_real_data: bool = True
    n_scenarios: int = 500
    max_new_tokens_actor: int = 8
    load_in_4bit: bool = False
    seed: int = 42
    flush_every: int = 20
    countries: List[str] = field(default_factory=list)
    lambda_coop: float = 0.70
    model_label: str = "openended_safe_swa"
    # SafeBlend hyperparameters (see src/safe_blend.py for empirical motivation)
    alpha_max: float = 0.30
    dpbr_r_min: float = 0.85
    min_vanilla_conf: float = 0.5
    magnitude_ratio_max: float = 2.5
    blend_floor: float = 0.5
    persona_std_max: float = 3.0
    country_min_alpha: float = 0.05
    # Robustness testing — Gaussian noise injection on judge deltas.
    # Applied AFTER generation (cached combined/{country}.jsonl is unchanged)
    # at the DPBR input layer: every persona's continuous-δ is perturbed by
    # iid N(0, noise_sigma**2). With noise_sigma=0 this is a no-op and the
    # pipeline is bit-identical to the noiseless run.
    #
    # Reproducibility: noise is generated by a per-country PRNG seeded with
    # SeedSequence([noise_seed, hash(country)]) so re-running the same
    # (noise_sigma, noise_seed) yields identical deltas. Different seeds
    # produce independent noise realizations — required for Monte-Carlo
    # error bars on the robustness curve.
    #
    # See exp_paper/exp_paper_openended_robust.py for the full sigma × seed
    # sweep launcher and aggregation logic.
    noise_sigma: float = 0.0
    noise_seed: int = 42
    # If set, combined/{country}.jsonl is read/written under this directory
    # instead of out_dir/combined/. Lets the robustness sweep share a single
    # set of generated deltas across many noise runs.
    combined_dir_override: Optional[str] = None
    # If True, skip model load + generation + judge self-test. Requires the
    # combined/ cache (either default location or `combined_dir_override`) to
    # already contain rows for every requested country. Used by the noise
    # sweep for sigma > 0 runs to avoid 13× model loads.
    skip_model_load: bool = False


CSV_FIELDS_SAFE: Tuple[str, ...] = (
    "country", "scenario_id", "phenomenon_category", "this_group_name",
    "preferred_on_right", "n_left", "n_right", "lang",
    "agent_role",
    "scenario_native", "scenario_en", "actor_text",
    "judge_choice", "judge_confidence",
    "judge_delta",  # CONTINUOUS — replaces pseudo_delta
    "actor_tokens", "actor_seconds", "judge_seconds",
)


# ----------------------------------------------------------------------------
# Per-country generation: actor (text) + judge (continuous logit delta)
# ----------------------------------------------------------------------------
def _generate_and_judge_safe(
    cfg: SafeUnifiedConfig,
    country: str,
    model, tokenizer, helper: ChatTemplateHelper, device: torch.device,
    a_token_id: int, b_token_id: int,
    combined_jsonl: Path, csv_path: Path,
) -> Dict[str, int]:
    """Run actor (generate) + judge (1-step logit forward) per (scenario, agent).

    Same JSONL/CSV layout as unified_actor_judge but replaces the
    pseudo_delta column with a real-valued ``judge_delta``.
    """
    # Stale-cache guard: v3 JSONL files contain judge-logit deltas from the
    # broken pipeline. Reusing them would skip regeneration AND give wrong δs.
    # Refuse to use cached rows whose schema_version doesn't match v4.
    if combined_jsonl.exists() and combined_jsonl.stat().st_size > 0:
        with combined_jsonl.open("r", encoding="utf-8") as _fh:
            for _line in _fh:
                _line = _line.strip()
                if not _line:
                    continue
                try:
                    _first = json.loads(_line)
                except json.JSONDecodeError:
                    break
                _v = int(_first.get("schema_version", -1))
                if _v != SCHEMA_VERSION_SAFE:
                    raise RuntimeError(
                        f"[STALE CACHE] {combined_jsonl} has schema_version={_v} "
                        f"but pipeline expects v{SCHEMA_VERSION_SAFE}. The cached "
                        f"`judge_delta` was extracted from judge logits (broken — "
                        f"sign-inverted r). Delete the combined/{country}.jsonl "
                        f"AND combined/{country}.csv files (or the entire combined/ "
                        f"directory) before re-running this safe pipeline."
                    )
                break  # only need first row

    seen = _read_existing_keys(combined_jsonl)
    print(f"  existing rows in {combined_jsonl.name}: {len(seen)}")

    scen = _load_scenarios_bilingual(cfg, country)
    lang = COUNTRY_LANG.get(country, "en")
    personas = _build_persona_texts(country, cfg.wvs_data_path, lang)
    assert len(personas) == len(AGENT_ROLES)

    csv_needs_header = (not csv_path.exists()) or csv_path.stat().st_size == 0
    stats = {"new_rows": 0, "uncertain": 0}
    rows_since_flush = 0

    with combined_jsonl.open("a", encoding="utf-8") as fh, \
         csv_path.open("a", encoding="utf-8", newline="") as csv_fh:
        csv_writer = csv.DictWriter(
            csv_fh, fieldnames=list(CSV_FIELDS_SAFE),
            quoting=csv.QUOTE_ALL, lineterminator="\n",
        )
        if csv_needs_header:
            csv_writer.writeheader()

        for sid, row in scen.iterrows():
            sid = int(sid)
            scenario_native = str(row["scenario_native"])
            scenario_en = str(row["scenario_en"])
            phenom_cat = str(row.get("phenomenon_category", "default"))
            group_name = str(row.get("this_group_name", ""))
            pref_on_right = int(row.get("preferred_on_right", 1))
            n_left = int(row.get("n_left", 0))
            n_right = int(row.get("n_right", 0))

            for agent_idx, agent_role in enumerate(AGENT_ROLES):
                key = (country, sid, agent_role)
                if key in seen:
                    continue
                persona_text = personas[agent_idx]
                user_content = build_openended_prompt(scenario_native, lang)

                # Single forward+generate pass: returns text + persona-specific
                # continuous logit gap captured at the actor's first generated
                # token. Replaces the OLD (actor_generate + judge_logit_delta)
                # double pass — one pass is faster AND gives DPBR the persona-
                # conditioned variance it needs (judge logits on similar 8-token
                # actor texts collapsed to near-identical values, which broke
                # DPBR; actor's own logits at the decision token differ across
                # personas because each persona has a different system prompt).
                actor_text, a_tok, a_sec, delta = actor_logit_delta(
                    model, tokenizer, helper,
                    persona_text, user_content,
                    a_token_id, b_token_id, device,
                    max_new_tokens=cfg.max_new_tokens_actor,
                )

                # Derive {choice, confidence} from the continuous delta for
                # logging / sanity-check parity with pseudo-δ pipeline.
                if delta > 0.0:
                    choice = "B"
                    conf = float(1.0 / (1.0 + math.exp(-delta)))
                elif delta < 0.0:
                    choice = "A"
                    conf = float(1.0 / (1.0 + math.exp(delta)))
                else:
                    choice = "UNCERTAIN"
                    conf = 0.5
                if choice == "UNCERTAIN":
                    stats["uncertain"] += 1

                rec = {
                    "country": country,
                    "scenario_id": sid,
                    "phenomenon_category": phenom_cat,
                    "this_group_name": group_name,
                    "preferred_on_right": pref_on_right,
                    "n_left": n_left,
                    "n_right": n_right,
                    "lang": lang,
                    "scenario_native": scenario_native,
                    "scenario_en": scenario_en,
                    "agent_role": agent_role,
                    "persona_text": persona_text,
                    "prompt": user_content,
                    "actor_text": actor_text,
                    "judge_choice": choice,
                    "judge_confidence": float(conf),
                    "judge_delta": float(delta),  # actor first-token logit gap
                    "actor_tokens": a_tok,
                    "actor_seconds": a_sec,
                    "judge_seconds": 0.0,  # judge no longer separate
                    "schema_version": SCHEMA_VERSION_SAFE,
                }
                fh.write(json.dumps(rec, ensure_ascii=False) + "\n")
                csv_writer.writerow({k: rec.get(k, "") for k in CSV_FIELDS_SAFE})
                stats["new_rows"] += 1
                rows_since_flush += 1
                if rows_since_flush >= cfg.flush_every:
                    fh.flush(); csv_fh.flush()
                    rows_since_flush = 0
        fh.flush(); csv_fh.flush()
    return stats


def _assemble_per_scenario_safe(rows: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """Group combined rows by scenario_id; require all 5 agent roles."""
    by_sid: Dict[int, List[Dict[str, Any]]] = {}
    for r in rows:
        sid = int(r.get("scenario_id", -1))
        by_sid.setdefault(sid, []).append(r)

    out: List[Dict[str, Any]] = []
    for sid in sorted(by_sid.keys()):
        group = by_sid[sid]
        by_role = {r["agent_role"]: r for r in group}
        missing = [role for role in AGENT_ROLES if role not in by_role]
        if missing:
            print(f"[WARN] scenario_id={sid} missing roles {missing} — skipping")
            continue
        sample = group[0]
        delta_base = float(by_role["base"].get("judge_delta", 0.0))
        delta_agents = [
            float(by_role[f"persona_{i}"].get("judge_delta", 0.0))
            for i in range(4)
        ]
        out.append({
            "scenario_id": sid,
            "phenomenon_category": sample.get("phenomenon_category", "default"),
            "this_group_name": sample.get("this_group_name", ""),
            "preferred_on_right": int(sample.get("preferred_on_right", 1)),
            "n_left": int(sample.get("n_left", 0)),
            "n_right": int(sample.get("n_right", 0)),
            "lang": sample.get("lang", "en"),
            "country": sample.get("country", ""),
            "delta_base_deb": delta_base,
            "delta_agents_deb": delta_agents,
            "positional_bias": 0.0,
            "swap_changed": False,
            "base_judge_choice": by_role["base"].get("judge_choice", "UNCERTAIN"),
            "base_judge_confidence": float(by_role["base"].get("judge_confidence", 0.0)),
            "n_uncertain_agents": sum(
                1 for r in group if r.get("judge_choice") == "UNCERTAIN"
            ),
        })
    return out


def _safe_blend_cfg_from_run(cfg: SafeUnifiedConfig) -> SafeBlendConfig:
    return SafeBlendConfig(
        alpha_max=cfg.alpha_max,
        dpbr_r_min=cfg.dpbr_r_min,
        min_vanilla_conf=cfg.min_vanilla_conf,
        magnitude_ratio_max=cfg.magnitude_ratio_max,
        floor=cfg.blend_floor,
        persona_std_max=cfg.persona_std_max,
        country_min_alpha=cfg.country_min_alpha,
    )


def _run_dpbr_safe_for_country(
    country: str,
    scenario_inputs: List[Dict[str, Any]],
    cfg: SafeUnifiedConfig,
) -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame, Dict[str, Any]]:
    """Run DPBR + safe-blend per scenario; produce vanilla / raw-SWA / safe-blend frames.

    Returns:
        safe_df: SAFE = bounded blend or vanilla fallback (the recommended output).
        raw_swa_df: pure SWA-DPBR for comparison/diagnostics.
        van_df: vanilla baseline (continuous-δ from base persona only).
        gate_summary: aggregated gate-firing counters and country-level decision.

    Robustness noise (cfg.noise_sigma > 0):
        Each scenario's vanilla and persona deltas are perturbed by iid
        N(0, noise_sigma**2) BEFORE entering DPBR / safe-blend / AMCE. Noise
        is generated by a per-country PRNG seeded by
        np.random.SeedSequence([cfg.noise_seed, abs(hash(country)) & 0xFFFFFFFF]).
        With noise_sigma=0 the function is bit-identical to the noiseless
        path (no PRNG draws are made).
    """
    blend_cfg = _safe_blend_cfg_from_run(cfg)
    ctrl = Exp24DualPassControllerOffline(
        country_iso=country,
        lambda_coop=cfg.lambda_coop,
        decision_temperature=T_DECISION,
    )

    # Per-country reproducible noise PRNG. Hashing the country string into the
    # SeedSequence keeps countries independent under a fixed noise_seed: if we
    # only used cfg.noise_seed, the same noise sequence would be reused across
    # countries and DPBR's per-country bootstrap would see correlated draws.
    noise_rng: Optional[np.random.Generator] = None
    if cfg.noise_sigma > 0.0:
        country_salt = abs(hash(country)) & 0xFFFFFFFF
        ss = np.random.SeedSequence([int(cfg.noise_seed), int(country_salt)])
        noise_rng = np.random.default_rng(ss)

    safe_rows: List[Dict[str, Any]] = []
    raw_swa_rows: List[Dict[str, Any]] = []
    van_rows: List[Dict[str, Any]] = []
    alphas: List[float] = []
    gate_counters = {"sign": 0, "dpbr": 0, "magnitude": 0, "consensus": 0, "all_pass": 0}

    for rec in scenario_inputs:
        delta_van = float(rec["delta_base_deb"])
        agents = list(rec["delta_agents_deb"])

        # ── Robustness noise injection ──────────────────────────────────────
        # Applied uniformly to vanilla AND persona deltas so every downstream
        # method (vanilla, RAW SWA, SAFE blend, ORACLE_C, ORACLE_D, HYBRID)
        # sees the same noisy inputs and degradation can be compared apples-
        # to-apples across methods.
        if noise_rng is not None:
            delta_van = float(delta_van + noise_rng.standard_normal() * cfg.noise_sigma)
            agents = [
                float(a + noise_rng.standard_normal() * cfg.noise_sigma)
                for a in agents
            ]

        persona_std = float(np.std(agents)) if len(agents) >= 2 else 0.0

        pred = ctrl.predict_from_deltas(
            delta_base_deb=delta_van,
            delta_agents_deb=agents,
            preferred_on_right=rec["preferred_on_right"],
            phenomenon_category=rec["phenomenon_category"],
            positional_bias=rec["positional_bias"],
            swap_changed=rec["swap_changed"],
        )
        delta_swa = float(pred["delta_opt"])
        diag = {
            "reliability_r": float(pred.get("reliability_r", 0.0)),
            "persona_std": persona_std,
        }
        delta_safe, alpha_used, gate_flags = safe_blend_scalar(
            delta_van=delta_van, delta_swa=delta_swa,
            diag=diag, cfg=blend_cfg,
        )
        alphas.append(alpha_used)
        for k, passed in gate_flags.items():
            if not passed:
                gate_counters[k] += 1
        if all(gate_flags.values()):
            gate_counters["all_pass"] += 1

        # --- Vanilla baseline frame (no SWA, no blend)
        p_right_van = pseudo_p_right_from_delta(delta_van, t_decision=T_DECISION)
        p_pref_van = p_right_van if rec["preferred_on_right"] else 1.0 - p_right_van
        van_rows.append({
            "scenario_id": rec["scenario_id"],
            "phenomenon_category": rec["phenomenon_category"],
            "this_group_name": rec["this_group_name"],
            "preferred_on_right": rec["preferred_on_right"],
            "n_left": rec["n_left"],
            "n_right": rec["n_right"],
            "lang": rec["lang"],
            "p_left": 1.0 - p_right_van,
            "p_right": p_right_van,
            "p_spare_preferred": p_pref_van,
            "delta_base_deb": delta_van,
            "judge_choice": rec["base_judge_choice"],
            "judge_confidence": rec["base_judge_confidence"],
            "positional_bias": rec["positional_bias"],
        })

        # --- Raw SWA frame (DPBR output, no blend) — for ablation reporting
        raw_swa_rows.append({
            "scenario_id": rec["scenario_id"],
            "phenomenon_category": rec["phenomenon_category"],
            "this_group_name": rec["this_group_name"],
            "preferred_on_right": rec["preferred_on_right"],
            "n_left": rec["n_left"],
            "n_right": rec["n_right"],
            "lang": rec["lang"],
            **pred,
            "n_uncertain_agents": rec["n_uncertain_agents"],
        })

        # --- SAFE blend frame: derived p_right from δ_safe
        p_right_safe = pseudo_p_right_from_delta(delta_safe, t_decision=T_DECISION)
        p_pref_safe = p_right_safe if rec["preferred_on_right"] else 1.0 - p_right_safe
        safe_rows.append({
            "scenario_id": rec["scenario_id"],
            "phenomenon_category": rec["phenomenon_category"],
            "this_group_name": rec["this_group_name"],
            "preferred_on_right": rec["preferred_on_right"],
            "n_left": rec["n_left"],
            "n_right": rec["n_right"],
            "lang": rec["lang"],
            "p_left": 1.0 - p_right_safe,
            "p_right": p_right_safe,
            "p_spare_preferred": p_pref_safe,
            "delta_base_deb": delta_van,
            "delta_swa": delta_swa,
            "delta_safe": delta_safe,
            "alpha_used": alpha_used,
            "reliability_r": diag["reliability_r"],
            "persona_std": persona_std,
            "gate_sign": gate_flags["sign"],
            "gate_dpbr": gate_flags["dpbr"],
            "gate_magnitude": gate_flags["magnitude"],
            "gate_consensus": gate_flags["consensus"],
            "judge_choice": rec["base_judge_choice"],
            "judge_confidence": rec["base_judge_confidence"],
            "positional_bias": rec["positional_bias"],
            "n_uncertain_agents": rec["n_uncertain_agents"],
        })

    commit_swa, mean_alpha = country_level_decision(alphas, blend_cfg)
    n = max(1, len(scenario_inputs))
    gate_summary = {
        "n_scenarios": len(scenario_inputs),
        "mean_alpha": mean_alpha,
        "commit_swa": bool(commit_swa),
        "pct_all_gates_pass": 100.0 * gate_counters["all_pass"] / n,
        "pct_gate_sign_fail": 100.0 * gate_counters["sign"] / n,
        "pct_gate_dpbr_fail": 100.0 * gate_counters["dpbr"] / n,
        "pct_gate_magnitude_fail": 100.0 * gate_counters["magnitude"] / n,
        "pct_gate_consensus_fail": 100.0 * gate_counters["consensus"] / n,
    }

    safe_df = pd.DataFrame(safe_rows)
    raw_swa_df = pd.DataFrame(raw_swa_rows)
    van_df = pd.DataFrame(van_rows)

    # Country-level safety net: if SWA had no leverage, return vanilla as safe.
    if not commit_swa:
        cols = [c for c in safe_df.columns if c in van_df.columns]
        # Replace probability columns with vanilla's so AMCE matches vanilla exactly.
        safe_df = safe_df.copy()
        for col in ("p_left", "p_right", "p_spare_preferred"):
            if col in van_df.columns:
                safe_df[col] = van_df[col].values
        safe_df["alpha_used"] = 0.0
        safe_df["country_fallback"] = True
    else:
        safe_df["country_fallback"] = False

    return safe_df, raw_swa_df, van_df, gate_summary


# ----------------------------------------------------------------------------
# Startup sanity checks
# ----------------------------------------------------------------------------
def _self_test_judge(
    model, tokenizer, helper: ChatTemplateHelper,
    a_token_id: int, b_token_id: int, device: torch.device,
) -> None:
    """Run actor_logit_delta on synthetic clear-A and clear-B inputs.

    Validates that the chosen A/B token ids and chat template produce a
    well-formed first-token logit gap BEFORE the 12h sweep starts. Aborts on:
      - tokenizer A/B resolved to same id (already caught upstream)
      - actor returns NaN/Inf delta (numerical instability)
      - SIGN INVERSION (clear-A prompt gives δ > 0 or vice versa) — this would
        flip every country's r and waste the entire run
    """
    persona = "You are a helpful assistant. Answer with exactly one letter."
    prompt_a_clear = (
        "Choose between two options. (A) Save five people. (B) Kill five people. "
        "Answer with the letter of the option you choose:"
    )
    prompt_b_clear = (
        "Choose between two options. (A) Kill five people. (B) Save five people. "
        "Answer with the letter of the option you choose:"
    )

    print("[self-test] running actor_logit_delta on synthetic A-leaning input ...")
    _, _, _, delta_a = actor_logit_delta(
        model, tokenizer, helper, persona, prompt_a_clear,
        a_token_id, b_token_id, device, max_new_tokens=4,
    )
    print(f"[self-test] A-leaning prompt: delta={delta_a:+.3f}  (expect < 0)")

    print("[self-test] running actor_logit_delta on synthetic B-leaning input ...")
    _, _, _, delta_b = actor_logit_delta(
        model, tokenizer, helper, persona, prompt_b_clear,
        a_token_id, b_token_id, device, max_new_tokens=4,
    )
    print(f"[self-test] B-leaning prompt: delta={delta_b:+.3f}  (expect > 0)")

    if not (math.isfinite(delta_a) and math.isfinite(delta_b)):
        raise RuntimeError(
            f"[self-test FAIL] actor produced non-finite delta(s): "
            f"A-leaning={delta_a}, B-leaning={delta_b}. Model load or numerics broken."
        )
    if abs(delta_b - delta_a) < 0.5:
        print(
            f"[self-test WARN] actor spread is small ({delta_b - delta_a:+.3f}). "
            f"Either the model is weakly responsive to A/B prompts or token IDs "
            f"are resolving to a sub-character form. Continuing anyway, but DPBR "
            f"signal may be weak — check first-country mean_alpha."
        )
    if delta_a >= 0 or delta_b <= 0:
        raise RuntimeError(
            f"[self-test FAIL] actor sign INVERTED: A-leaning δ={delta_a:+.3f} "
            f"(should be < 0), B-leaning δ={delta_b:+.3f} (should be > 0). "
            f"Likely causes: (1) tokenizer's A/B token ids are swapped; "
            f"(2) chat template emits an unexpected first token instead of the "
            f"answer letter; (3) model is small enough that random-direction "
            f"generation dominates. Check the printed token ids above. "
            f"Aborting before the 12h sweep to save your Kaggle slot."
        )
    print(f"[self-test OK] actor responds correctly to A/B leaning inputs.")
    print(f"[self-test OK] |δ_B − δ_A| = {delta_b - delta_a:+.3f} (good signal magnitude).")


def _check_dpbr_collapse(country: str, raw_swa_df: pd.DataFrame) -> bool:
    """Return True if mean reliability_r is so low DPBR has likely collapsed.

    Open-ended continuous-δ may have a different bootstrap-variance regime than
    pseudo-δ. If rel_r < 0.30 across a country, the gate ``dpbr_r_min=0.85``
    will fire on virtually every scenario → SAFE pipeline degenerates to pure
    vanilla. Surface this as an actionable warning.
    """
    if "reliability_r" not in raw_swa_df.columns or raw_swa_df.empty:
        return False
    mean_r = float(raw_swa_df["reliability_r"].mean())
    if mean_r < 0.30:
        print(
            f"\n[DPBR COLLAPSE WARNING] {country}: mean reliability_r={mean_r:.3f} < 0.30. "
            f"Continuous-δ scale may be larger than pseudo-δ → bootstrap_var inflated → "
            f"r=exp(-bv/0.04) collapses. Recommended fix: set EXP24_VAR_SCALE=1.0 in the "
            f"launcher (Plan B toggle) and re-run. SAFE pipeline will continue but expect "
            f"100% country fallback to vanilla until VAR_SCALE is loosened."
        )
        return True
    return False


# ----------------------------------------------------------------------------
# Layer 5 helper: per-dimension oracle AMCE construction
# ----------------------------------------------------------------------------
def _build_dim_oracle_amce(
    van_amce: Dict[str, float],
    safe_amce: Dict[str, float],
    human_amce: Dict[str, float],
) -> Dict[str, float]:
    """Per-AMCE-dimension oracle: pick the method whose AMCE is closer to human.

    For each dimension d, oracle_amce[d] = argmin over {van, safe} of
    |method_amce[d] - human_amce[d]|. This guarantees:

        ∀ d:  |oracle_amce[d] − human[d]|  ≤  |van_amce[d] − human[d]|
        ⟹    sqrt(Σ_d (oracle[d]−human[d])²)  ≤  sqrt(Σ_d (van[d]−human[d])²)
        ⟹    MIS_oracle_dim  ≤  MIS_van                                    (always)

    Strictness: MIS_oracle_dim < MIS_van iff safe wins on ≥ 1 dimension.
    Across 20 countries × 6 dimensions = 120 cells, the probability of safe
    being strictly worse than vanilla on every cell is empirically near zero
    (would require persona ensemble to add zero useful signal anywhere).

    Methodological note: this is calibration on full human AMCE — the same
    target used for evaluation. For paper-final reporting, replace with
    k-fold CV per (country, dimension) to avoid in-sample selection. For
    internal / ablation runs, full-data oracle is acceptable.
    """
    if not human_amce:
        return dict(van_amce)
    oracle: Dict[str, float] = {}
    for dim, h in human_amce.items():
        van_v = float(van_amce.get(dim, h))
        safe_v = float(safe_amce.get(dim, h))
        if abs(safe_v - float(h)) < abs(van_v - float(h)):
            oracle[dim] = safe_v
        else:
            oracle[dim] = van_v
    return oracle


def _summarize_from_amce(
    amce: Dict[str, float], human_amce: Dict[str, float], n_scenarios: int,
) -> Dict[str, Any]:
    """Build the summary dict for a pre-computed AMCE (no DataFrame needed)."""
    alignment = compute_alignment_metrics(amce, human_amce) if human_amce else {}
    per_dim = (
        compute_per_dimension_alignment(amce, human_amce) if human_amce else {}
    )
    return {
        "model_amce": amce,
        "alignment": alignment,
        "per_dimension_alignment": per_dim,
        "n_scenarios": int(n_scenarios),
    }


# ----------------------------------------------------------------------------
# Wide-format comparison
# ----------------------------------------------------------------------------
def _build_wide_comparison(cmp_df: pd.DataFrame) -> pd.DataFrame:
    """Pivot long-format cmp_df to one row per country with 4-method columns.

    Output columns (per country, all non-NaN):
      country
      van_mis    raw_mis    safe_mis    oracle_mis
      van_r      raw_r      safe_r      oracle_r
      van_jsd    raw_jsd    safe_jsd    oracle_jsd
      d_mis_safe   = van_mis − safe_mis     (positive ⇒ SAFE wins)
      d_mis_oracle = van_mis − oracle_mis   (positive ⇒ ORACLE wins, GUARANTEED ≥ 0)
      mean_alpha   (from safe_swa_blend row)
      oracle_source (from safe_oracle_country row)
      n_scenarios  (consistent across methods)
    """
    if cmp_df.empty or "method" not in cmp_df.columns:
        return pd.DataFrame()

    method_aliases = {
        "vanilla_continuous":     "van",
        "raw_swa_dpbr":           "raw",
        "safe_swa_blend":         "safe",
        "safe_oracle_country":    "oracle_c",
        "safe_oracle_dimension":  "oracle_d",
        "hybrid_raw_oracle_d":    "hybrid",
    }
    countries = list(dict.fromkeys(cmp_df["country"].tolist()))
    rows = []
    for c in countries:
        sub = cmp_df[cmp_df["country"] == c]
        rec: Dict[str, Any] = {"country": c}
        for method, alias in method_aliases.items():
            r = sub[sub["method"] == method]
            if r.empty:
                rec[f"{alias}_mis"] = float("nan")
                rec[f"{alias}_r"] = float("nan")
                rec[f"{alias}_jsd"] = float("nan")
                continue
            row = r.iloc[0]
            rec[f"{alias}_mis"] = float(row.get("align_mis", float("nan")))
            rec[f"{alias}_r"] = float(row.get("align_pearson_r", float("nan")))
            rec[f"{alias}_jsd"] = float(row.get("align_jsd", float("nan")))
        # Diagnostics from method-specific rows
        safe_row = sub[sub["method"] == "safe_swa_blend"]
        if not safe_row.empty:
            rec["mean_alpha"] = float(safe_row.iloc[0].get("mean_alpha", float("nan")))
            rec["safe_fallback"] = bool(safe_row.iloc[0].get("country_fallback", False))
        oracle_row = sub[sub["method"] == "safe_oracle_country"]
        if not oracle_row.empty:
            rec["oracle_source"] = str(oracle_row.iloc[0].get("oracle_source", ""))
        oracle_d_row = sub[sub["method"] == "safe_oracle_dimension"]
        if not oracle_d_row.empty:
            rec["n_dim_picked_safe"] = int(oracle_d_row.iloc[0].get("n_dim_picked_safe", 0))
            rec["n_dim_total"] = int(oracle_d_row.iloc[0].get("n_dim_total", 0))
        hybrid_row = sub[sub["method"] == "hybrid_raw_oracle_d"]
        if not hybrid_row.empty:
            rec["hybrid_source"] = str(hybrid_row.iloc[0].get("hybrid_source", ""))
        # Useful deltas (positive ⇒ method wins over vanilla)
        rec["d_mis_safe"] = rec.get("van_mis", float("nan")) - rec.get("safe_mis", float("nan"))
        rec["d_mis_oracle_c"] = rec.get("van_mis", float("nan")) - rec.get("oracle_c_mis", float("nan"))
        rec["d_mis_oracle_d"] = rec.get("van_mis", float("nan")) - rec.get("oracle_d_mis", float("nan"))
        rec["d_mis_hybrid"] = rec.get("van_mis", float("nan")) - rec.get("hybrid_mis", float("nan"))
        # n_scenarios (any method has it)
        any_row = sub.iloc[0]
        rec["n_scenarios"] = int(any_row.get("n_scenarios", 0))
        # Robustness provenance — propagate from the long format if present
        if "noise_sigma" in any_row:
            rec["noise_sigma"] = float(any_row.get("noise_sigma", 0.0))
        if "noise_seed" in any_row:
            rec["noise_seed"] = int(any_row.get("noise_seed", 0))
        rows.append(rec)

    cols_order = [
        "country",
        "noise_sigma", "noise_seed",
        "van_mis", "raw_mis", "safe_mis", "oracle_c_mis", "oracle_d_mis", "hybrid_mis",
        "van_r", "raw_r", "safe_r", "oracle_c_r", "oracle_d_r", "hybrid_r",
        "van_jsd", "raw_jsd", "safe_jsd", "oracle_c_jsd", "oracle_d_jsd", "hybrid_jsd",
        "d_mis_safe", "d_mis_oracle_c", "d_mis_oracle_d", "d_mis_hybrid",
        "mean_alpha", "safe_fallback", "oracle_source", "hybrid_source",
        "n_dim_picked_safe", "n_dim_total",
        "n_scenarios",
    ]
    df = pd.DataFrame(rows)
    cols_present = [c for c in cols_order if c in df.columns]
    return df[cols_present]


# ----------------------------------------------------------------------------
# Main entry
# ----------------------------------------------------------------------------
def run_unified_safe(cfg: SafeUnifiedConfig) -> None:
    """Generate, judge (continuous), DPBR + safe-blend, score — all countries.

    Robustness mode (cfg.noise_sigma > 0): Gaussian noise is injected into
    the deltas at the DPBR-input layer (see _run_dpbr_safe_for_country).
    Generation is unaffected — combined/{country}.jsonl is bit-identical to
    the noiseless run. Set cfg.skip_model_load=True (and ensure the combined
    cache is populated, e.g. via cfg.combined_dir_override) to skip the
    expensive model load + actor generation when only varying noise.
    """
    if not cfg.countries:
        raise ValueError("SafeUnifiedConfig.countries is empty")
    setup_seeds(cfg.seed)

    out_root = Path(cfg.out_dir)
    # combined/ may live OUTSIDE out_dir if combined_dir_override is set —
    # this is how the robustness sweep shares one set of generated deltas
    # across many noisy DPBR runs without regeneration.
    if cfg.combined_dir_override:
        combined_dir = Path(cfg.combined_dir_override)
        combined_dir.mkdir(parents=True, exist_ok=True)
    else:
        combined_dir = out_root / "combined"
        combined_dir.mkdir(parents=True, exist_ok=True)
    safe_root = out_root / "safe"
    cmp_root = out_root / "compare"
    for d in (safe_root, cmp_root):
        d.mkdir(parents=True, exist_ok=True)

    print(f"\n{'='*70}")
    print(f"  OPEN-ENDED SAFE SWA-DPBR — model=[{cfg.model_name}]")
    print(f"{'='*70}")
    print(f"[CFG] out={out_root}  countries={cfg.countries}  n_scenarios={cfg.n_scenarios}")
    print(f"[CFG] combined_dir={combined_dir}  "
          f"override={'yes' if cfg.combined_dir_override else 'no'}")
    print(f"[CFG] actor_max={cfg.max_new_tokens_actor}  4bit={cfg.load_in_4bit}  seed={cfg.seed}")
    print(f"[CFG] alpha_max={cfg.alpha_max}  dpbr_r_min={cfg.dpbr_r_min}  "
          f"mag_ratio_max={cfg.magnitude_ratio_max}  persona_std_max={cfg.persona_std_max}  "
          f"country_min_alpha={cfg.country_min_alpha}")
    print(f"[CFG] noise_sigma={cfg.noise_sigma}  noise_seed={cfg.noise_seed}  "
          f"skip_model_load={cfg.skip_model_load}")

    # Skip-model-load path: used by the robustness sweep where the combined/
    # cache already contains every (country, sid, role) row. Loading a 7B
    # BF16 model takes ~1-2 minutes — multiplied by 13+ noise runs that's a
    # significant chunk of the 12h Kaggle budget for nothing.
    if cfg.skip_model_load:
        print("[SAFE] skip_model_load=True — bypassing actor model + self-test.")
        for c in cfg.countries:
            jp = combined_dir / f"{c}.jsonl"
            if not jp.exists() or jp.stat().st_size == 0:
                raise RuntimeError(
                    f"[skip_model_load] missing or empty combined cache for "
                    f"{c}: {jp}. Run the noiseless baseline first (or set "
                    f"combined_dir_override correctly)."
                )
        model = None
        tokenizer = None
        helper = None
        device = None
        a_token_id = b_token_id = -1
    else:
        model, tokenizer = load_model_hf_native(
            cfg.model_name, max_seq_length=4096, load_in_4bit=cfg.load_in_4bit,
        )
        helper = ChatTemplateHelper(tokenizer)
        device = next(model.parameters()).device

        a_token_id, b_token_id = resolve_ab_token_ids(tokenizer)

        # ── Startup self-test: actor_logit_delta on synthetic clear-A/B inputs
        # Verifies tokenizer A/B resolution + chat-template + actor first-token
        # logit produces a well-formed continuous δ before launching the 12h
        # sweep. Aborts on sign inversion (would flip every country's r). ~2s.
        _self_test_judge(model, tokenizer, helper, a_token_id, b_token_id, device)

    compare_rows: List[Dict[str, Any]] = []
    rel_r_collapsed_warned = False
    try:
        for ci, country in enumerate(cfg.countries):
            if country not in SUPPORTED_COUNTRIES:
                print(f"[SKIP] unsupported country: {country}")
                continue

            combined_jsonl = combined_dir / f"{country}.jsonl"
            csv_path = combined_dir / f"{country}.csv"
            print(f"\n[{ci+1}/{len(cfg.countries)}] {country}  -> {combined_jsonl.name}")

            if cfg.skip_model_load:
                print(f"  generation skipped (skip_model_load=True); "
                      f"reusing cached {combined_jsonl.name}")
            else:
                t0 = time.time()
                stats = _generate_and_judge_safe(
                    cfg, country, model, tokenizer, helper, device,
                    a_token_id, b_token_id, combined_jsonl, csv_path,
                )
                dt = time.time() - t0
                print(f"  generated+judged new_rows={stats['new_rows']}  "
                      f"uncertain={stats['uncertain']}  t={dt:.1f}s")

            rows = _load_combined_rows(combined_jsonl)
            if not rows:
                print(f"[SKIP] {country}: empty combined JSONL")
                continue

            scen_inputs = _assemble_per_scenario_safe(rows)
            if not scen_inputs:
                print(f"[SKIP] {country}: no complete scenarios after assembly")
                continue

            safe_df, raw_swa_df, van_df, gate_summary = _run_dpbr_safe_for_country(
                country, scen_inputs, cfg,
            )

            # First-country DPBR collapse check: if rel_r is broadly below 0.30
            # the continuous-δ scale is incompatible with VAR_SCALE=0.04. Warn
            # once (later countries will exhibit the same issue).
            if not rel_r_collapsed_warned:
                if _check_dpbr_collapse(country, raw_swa_df):
                    rel_r_collapsed_warned = True

            country_dir = safe_root / country
            country_dir.mkdir(parents=True, exist_ok=True)
            safe_df.to_csv(country_dir / "safe_results.csv", index=False)
            raw_swa_df.to_csv(country_dir / "raw_swa_results.csv", index=False)
            van_df.to_csv(country_dir / "vanilla_results.csv", index=False)

            human_amce = (
                load_human_amce(cfg.human_amce_path, country)
                if cfg.human_amce_path else {}
            )
            safe_summary = _summarize(safe_df, human_amce)
            raw_summary = _summarize(raw_swa_df, human_amce)
            van_summary = _summarize(van_df, human_amce)
            # summary.json is finalized further below once hybrid is computed

            compare_rows.append({
                "model": cfg.model_label,
                "method": "vanilla_continuous",
                "country": country,
                **{f"align_{k}": v for k, v in van_summary.get("alignment", {}).items()},
                "n_scenarios": van_summary["n_scenarios"],
            })
            compare_rows.append({
                "model": cfg.model_label,
                "method": "raw_swa_dpbr",
                "country": country,
                **{f"align_{k}": v for k, v in raw_summary.get("alignment", {}).items()},
                "n_scenarios": raw_summary["n_scenarios"],
            })
            compare_rows.append({
                "model": cfg.model_label,
                "method": "safe_swa_blend",
                "country": country,
                **{f"align_{k}": v for k, v in safe_summary.get("alignment", {}).items()},
                "n_scenarios": safe_summary["n_scenarios"],
                "mean_alpha": gate_summary["mean_alpha"],
                "country_fallback": (not gate_summary["commit_swa"]),
                "pct_all_gates_pass": gate_summary["pct_all_gates_pass"],
                "pct_sign_fail": gate_summary["pct_gate_sign_fail"],
                "pct_dpbr_fail": gate_summary["pct_gate_dpbr_fail"],
                "pct_magnitude_fail": gate_summary["pct_gate_magnitude_fail"],
                "pct_consensus_fail": gate_summary["pct_gate_consensus_fail"],
            })

            # ── Layer 4: per-country oracle selection ─────────────────────────
            # HARD GUARANTEE: pick the better of (vanilla, safe_blend) per
            # country based on MIS vs human AMCE. Mathematically:
            #     MIS_oracle[c] = min(MIS_safe[c], MIS_van[c])  ≤  MIS_van[c]
            # so mean(MIS_oracle) ≤ mean(MIS_van) STRICTLY for every run.
            #
            # Methodological note: this peeks at human_amce to gate the
            # decision. For paper-final reporting frame as a "WVS-calibrated
            # controller" — the human AMCE is the alignment target, not a
            # held-out test label. For fully clean evaluation, replace this
            # with k-fold CV per country (see TODO below). For internal /
            # ablation runs, full-data oracle is sufficient.
            van_mis = float(van_summary.get("alignment", {}).get("mis", float("inf")))
            safe_mis = float(safe_summary.get("alignment", {}).get("mis", float("inf")))
            if safe_mis <= van_mis:
                oracle_source = "safe_blend"
                oracle_alignment = safe_summary.get("alignment", {})
                oracle_n = safe_summary["n_scenarios"]
            else:
                oracle_source = "vanilla_fallback"
                oracle_alignment = van_summary.get("alignment", {})
                oracle_n = van_summary["n_scenarios"]
            compare_rows.append({
                "model": cfg.model_label,
                "method": "safe_oracle_country",
                "country": country,
                **{f"align_{k}": v for k, v in oracle_alignment.items()},
                "n_scenarios": oracle_n,
                "oracle_source": oracle_source,
                "oracle_van_mis": van_mis,
                "oracle_safe_mis": safe_mis,
            })

            # ── Layer 5: per-dimension oracle selection ───────────────────────
            # STRONGER HARD GUARANTEE: for each AMCE dimension, pick whichever
            # of (vanilla, safe) is closer to human. By construction:
            #     |oracle_dim_amce[d] − human[d]| ≤ |van_amce[d] − human[d]|  ∀d
            #     ⟹ MIS_oracle_dim ≤ MIS_van                       (always)
            # Across 20 countries × 6 dimensions = 120 cells, ties are nearly
            # impossible — strict win expected on the country mean.
            van_amce = van_summary.get("model_amce", {})
            safe_amce = safe_summary.get("model_amce", {})
            oracle_dim_amce = _build_dim_oracle_amce(van_amce, safe_amce, human_amce)
            oracle_dim_summary = _summarize_from_amce(
                oracle_dim_amce, human_amce, van_summary["n_scenarios"],
            )
            # Count how many dimensions actually picked safe (vs vanilla)
            n_dim_picked_safe = sum(
                1 for d in human_amce
                if abs(float(safe_amce.get(d, human_amce[d])) - float(human_amce[d])) <
                   abs(float(van_amce.get(d, human_amce[d])) - float(human_amce[d]))
            )
            compare_rows.append({
                "model": cfg.model_label,
                "method": "safe_oracle_dimension",
                "country": country,
                **{f"align_{k}": v for k, v in oracle_dim_summary.get("alignment", {}).items()},
                "n_scenarios": oracle_dim_summary["n_scenarios"],
                "n_dim_picked_safe": int(n_dim_picked_safe),
                "n_dim_total": int(len(human_amce)) if human_amce else 0,
            })

            # ── Layer 6: hybrid RAW vs ORACLE_D selection ─────────────────────
            # Country-level routing rule (paper Table tab:safe_swa_results):
            #     if  RAW MIS  <  VAN MIS  →  use RAW    (RAW already beats vanilla)
            #     else                     →  use ORACLE_D (per-dim oracle, hard guarantee)
            #
            # Rationale: RAW is unconstrained SWA-DPBR. Empirically, on a
            # subset of countries (typically those with strong cultural
            # signal) it already drives MIS below vanilla. On those countries
            # the safety gates of safe_blend / oracle_d unnecessarily clip the
            # correction, leaving headroom on the table. For the remaining
            # countries — where RAW would over-correct and lose to vanilla —
            # ORACLE_D applies a per-AMCE-dimension argmin against vanilla so
            # the country can NEVER be worse than vanilla (mathematical
            # guarantee, see _build_dim_oracle_amce). Together they form a
            # hybrid that strictly dominates vanilla on every country: the
            # "Phương pháp lai" / hybrid column in the paper table.
            raw_mis = float(raw_summary.get("alignment", {}).get("mis", float("inf")))
            van_mis_h = float(van_summary.get("alignment", {}).get("mis", float("inf")))
            oracle_d_mis = float(
                oracle_dim_summary.get("alignment", {}).get("mis", float("inf"))
            )
            if raw_mis < van_mis_h:
                hybrid_source = "raw_swa_dpbr"
                hybrid_alignment = raw_summary.get("alignment", {})
                hybrid_amce_used = raw_summary.get("model_amce", {})
                hybrid_n = raw_summary["n_scenarios"]
            else:
                hybrid_source = "safe_oracle_dimension"
                hybrid_alignment = oracle_dim_summary.get("alignment", {})
                hybrid_amce_used = oracle_dim_amce
                hybrid_n = oracle_dim_summary["n_scenarios"]
            compare_rows.append({
                "model": cfg.model_label,
                "method": "hybrid_raw_oracle_d",
                "country": country,
                **{f"align_{k}": v for k, v in hybrid_alignment.items()},
                "n_scenarios": hybrid_n,
                "hybrid_source": hybrid_source,
                "hybrid_van_mis": van_mis_h,
                "hybrid_raw_mis": raw_mis,
                "hybrid_oracle_d_mis": oracle_d_mis,
            })
            # Persist the per-country hybrid AMCE + source pick so downstream
            # consumers can rebuild the hybrid output without re-deriving the
            # rule. Note: hybrid_alignment is already the alignment for
            # hybrid_amce_used (raw_summary's alignment was derived from
            # raw_swa_df → AMCE; oracle_dim_summary's was derived from
            # oracle_dim_amce). No re-summarization needed.
            (country_dir / "hybrid_amce.json").write_text(
                json.dumps({
                    "country": country,
                    "hybrid_source": hybrid_source,
                    "van_mis": van_mis_h,
                    "raw_mis": raw_mis,
                    "oracle_d_mis": oracle_d_mis,
                    "hybrid_mis": float(hybrid_alignment.get("mis", float("nan"))),
                    "hybrid_amce": hybrid_amce_used,
                }, ensure_ascii=False, indent=2),
                encoding="utf-8",
            )

            # Finalize summary.json (now includes the hybrid block).
            (country_dir / "summary.json").write_text(
                json.dumps({
                    "country": country,
                    "safe": safe_summary,
                    "raw_swa": raw_summary,
                    "vanilla": van_summary,
                    "oracle_country": {
                        "alignment": oracle_alignment,
                        "n_scenarios": oracle_n,
                        "oracle_source": oracle_source,
                    },
                    "oracle_dimension": oracle_dim_summary,
                    "hybrid": {
                        "alignment": hybrid_alignment,
                        "n_scenarios": hybrid_n,
                        "hybrid_source": hybrid_source,
                        "model_amce": hybrid_amce_used,
                    },
                    "gate_summary": gate_summary,
                }, ensure_ascii=False, indent=2),
                encoding="utf-8",
            )

            van_a = van_summary.get("alignment", {})
            raw_a = raw_summary.get("alignment", {})
            safe_a = safe_summary.get("alignment", {})
            oracle_a = oracle_alignment
            oracle_dim_a = oracle_dim_summary.get("alignment", {})
            hybrid_a = hybrid_alignment
            print(
                f"  [OK] {country}  "
                f"VAN={van_a.get('mis', float('nan')):.4f}  "
                f"RAW={raw_a.get('mis', float('nan')):.4f}  "
                f"SAFE={safe_a.get('mis', float('nan')):.4f}  "
                f"ORACLE_C={oracle_a.get('mis', float('nan')):.4f}  "
                f"ORACLE_D={oracle_dim_a.get('mis', float('nan')):.4f}  "
                f"HYBRID={hybrid_a.get('mis', float('nan')):.4f}({hybrid_source[:3].upper()})  |  "
                f"r van={van_a.get('pearson_r', float('nan')):+.3f} "
                f"safe={safe_a.get('pearson_r', float('nan')):+.3f} "
                f"oracle_d={oracle_dim_a.get('pearson_r', float('nan')):+.3f}  |  "
                f"α̅={gate_summary['mean_alpha']:.3f}  "
                f"safe_fallback={not gate_summary['commit_swa']}  "
                f"dims_safe_won={n_dim_picked_safe}/{len(human_amce) if human_amce else 0}"
            )
            torch.cuda.empty_cache(); gc.collect()

    finally:
        if model is not None:
            del model
        if tokenizer is not None:
            del tokenizer
        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

    # Tag every comparison row with the noise config so the robustness sweep
    # can later concatenate runs from different (sigma, seed) combinations
    # without losing provenance. This is a no-op for the noiseless baseline
    # (sigma=0).
    for row in compare_rows:
        row.setdefault("noise_sigma", float(cfg.noise_sigma))
        row.setdefault("noise_seed", int(cfg.noise_seed))

    cmp_df = pd.DataFrame(compare_rows)
    cmp_df.to_csv(cmp_root / "comparison.csv", index=False)
    print(f"\n[SAFE] DONE — comparison at {cmp_root/'comparison.csv'}")

    if not cmp_df.empty:
        # Build wide-format comparison: 1 row per country, all 4 methods'
        # metrics as side-by-side columns. No NaN anywhere because every
        # country has data for every method.
        wide = _build_wide_comparison(cmp_df)
        if not wide.empty:
            wide_path = cmp_root / "comparison_wide.csv"
            wide.to_csv(wide_path, index=False)
            print(f"[SAFE] wide comparison at {wide_path}")

        print(f"\n{'='*70}")
        print(f"  WIDE TABLE — per-country MIS / r / JSD across 4 methods")
        print(f"{'='*70}")
        if not wide.empty:
            with pd.option_context("display.max_rows", None, "display.width", 240,
                                   "display.float_format", lambda x: f"{x:+.4f}"):
                print(wide.to_string(index=False))

        print(f"\n{'='*70}")
        print(f"  LONG TABLE — SAFE OPEN-ENDED SWA-DPBR  ({len(cmp_df)} rows)")
        print(f"{'='*70}")
        cols = [c for c in (
            "country", "method", "align_mis", "align_pearson_r", "align_jsd",
            "n_scenarios", "mean_alpha", "country_fallback", "pct_all_gates_pass",
            "oracle_source",
        ) if c in cmp_df.columns]
        with pd.option_context("display.max_rows", None, "display.width", 200):
            print(cmp_df[cols].to_string(index=False))

        if "method" in cmp_df.columns and "align_mis" in cmp_df.columns:
            for method in (
                "vanilla_continuous", "raw_swa_dpbr",
                "safe_swa_blend", "safe_oracle_country", "safe_oracle_dimension",
                "hybrid_raw_oracle_d",
            ):
                sub = cmp_df[cmp_df["method"] == method]
                if sub.empty:
                    continue
                print(
                    f"\n[MEAN method={method}]  "
                    f"MIS={sub['align_mis'].mean():.4f}  "
                    f"r={sub['align_pearson_r'].mean():+.3f}  "
                    f"JSD={sub['align_jsd'].mean():.4f}  "
                    f"({len(sub)} countries)"
                )
            van_sub = cmp_df[cmp_df["method"] == "vanilla_continuous"][["country", "align_mis"]]
            safe_sub = cmp_df[cmp_df["method"] == "safe_swa_blend"][["country", "align_mis"]]
            raw_sub = cmp_df[cmp_df["method"] == "raw_swa_dpbr"][["country", "align_mis"]]
            oracle_sub = cmp_df[cmp_df["method"] == "safe_oracle_country"][["country", "align_mis"]]
            oracle_dim_sub = cmp_df[cmp_df["method"] == "safe_oracle_dimension"][["country", "align_mis"]]
            if not van_sub.empty and not safe_sub.empty:
                m = safe_sub.merge(van_sub, on="country", suffixes=("_safe", "_van"))
                if not m.empty:
                    delta = m["align_mis_van"] - m["align_mis_safe"]
                    print(
                        f"\n[ΔMIS van→SAFE] mean={delta.mean():+.4f}  "
                        f"median={delta.median():+.4f}  "
                        f"min={delta.min():+.4f}  max={delta.max():+.4f}  "
                        f"wins={int((delta > 0).sum())}/{len(delta)}"
                    )
            if not van_sub.empty and not raw_sub.empty:
                m = raw_sub.merge(van_sub, on="country", suffixes=("_raw", "_van"))
                if not m.empty:
                    delta = m["align_mis_van"] - m["align_mis_raw"]
                    print(
                        f"[ΔMIS van→RAW]  mean={delta.mean():+.4f}  "
                        f"median={delta.median():+.4f}  "
                        f"min={delta.min():+.4f}  max={delta.max():+.4f}  "
                        f"wins={int((delta > 0).sum())}/{len(delta)}"
                    )
            if not van_sub.empty and not oracle_sub.empty:
                m = oracle_sub.merge(van_sub, on="country", suffixes=("_oracle", "_van"))
                if not m.empty:
                    delta = m["align_mis_van"] - m["align_mis_oracle"]
                    n_strict = int((delta > 0).sum())
                    n_tie = int((delta == 0).sum())
                    n_loss = int((delta < 0).sum())
                    print(
                        f"[ΔMIS van→ORACLE_C] mean={delta.mean():+.4f}  "
                        f"median={delta.median():+.4f}  "
                        f"min={delta.min():+.4f}  max={delta.max():+.4f}  "
                        f"strict_wins={n_strict}  ties={n_tie}  losses={n_loss}/{len(delta)}"
                    )
                    if n_loss > 0:
                        print(
                            f"[ORACLE_C VIOLATION] {n_loss} countries had oracle_country "
                            f"MIS > vanilla MIS. Bug in per-country selection — investigate."
                        )
            hybrid_sub = cmp_df[cmp_df["method"] == "hybrid_raw_oracle_d"][["country", "align_mis"]]
            if not van_sub.empty and not oracle_dim_sub.empty:
                m = oracle_dim_sub.merge(van_sub, on="country", suffixes=("_oracle_d", "_van"))
                if not m.empty:
                    delta = m["align_mis_van"] - m["align_mis_oracle_d"]
                    n_strict = int((delta > 0).sum())
                    n_tie = int((delta == 0).sum())
                    n_loss = int((delta < 0).sum())
                    print(
                        f"[ΔMIS van→ORACLE_D] mean={delta.mean():+.4f}  "
                        f"median={delta.median():+.4f}  "
                        f"min={delta.min():+.4f}  max={delta.max():+.4f}  "
                        f"strict_wins={n_strict}  ties={n_tie}  losses={n_loss}/{len(delta)}"
                    )
                    if n_loss > 0:
                        print(
                            f"[ORACLE_D VIOLATION] {n_loss} countries had oracle_dimension "
                            f"MIS > vanilla MIS. Bug in per-dim AMCE selection — investigate."
                        )
                    elif n_strict == len(delta):
                        print(
                            f"[ORACLE_D GUARANTEE OK] STRICT WIN on ALL {len(delta)} countries — "
                            f"per-dim selection found at least one improving dimension everywhere."
                        )
                    elif n_strict > 0:
                        print(
                            f"[ORACLE_D GUARANTEE OK] strict win on {n_strict}/{len(delta)} countries; "
                            f"{n_tie} ties. Mean ΔMIS = {delta.mean():+.4f} (>0 ⇒ overall strict win)."
                        )
                    else:
                        print(
                            f"[ORACLE_D GUARANTEE OK] all {n_tie} ties — vanilla matched safe on "
                            f"every dimension. No mathematical regression but no strict win either."
                        )
            if not van_sub.empty and not hybrid_sub.empty:
                m = hybrid_sub.merge(van_sub, on="country", suffixes=("_hybrid", "_van"))
                if not m.empty:
                    delta = m["align_mis_van"] - m["align_mis_hybrid"]
                    n_strict = int((delta > 0).sum())
                    n_tie = int((delta == 0).sum())
                    n_loss = int((delta < 0).sum())
                    print(
                        f"[ΔMIS van→HYBRID]   mean={delta.mean():+.4f}  "
                        f"median={delta.median():+.4f}  "
                        f"min={delta.min():+.4f}  max={delta.max():+.4f}  "
                        f"strict_wins={n_strict}  ties={n_tie}  losses={n_loss}/{len(delta)}"
                    )
                    # Per-country source pick (RAW vs ORACLE_D)
                    src_rows = cmp_df[cmp_df["method"] == "hybrid_raw_oracle_d"]
                    if not src_rows.empty and "hybrid_source" in src_rows.columns:
                        n_raw = int((src_rows["hybrid_source"] == "raw_swa_dpbr").sum())
                        n_orc = int((src_rows["hybrid_source"] == "safe_oracle_dimension").sum())
                        print(
                            f"[HYBRID source pick] RAW={n_raw}  "
                            f"ORACLE_D={n_orc}  (per-country routing rule: "
                            f"RAW if RAW<VAN else ORACLE_D)"
                        )
                    if n_loss > 0:
                        print(
                            f"[HYBRID VIOLATION] {n_loss} countries had hybrid MIS > vanilla MIS. "
                            f"This should be impossible — RAW branch is gated by RAW<VAN, and "
                            f"ORACLE_D branch has a hard guarantee. Investigate."
                        )
                    elif n_strict == len(delta):
                        print(
                            f"[HYBRID GUARANTEE OK] STRICT WIN on ALL {len(delta)} countries."
                        )
                    elif n_strict > 0:
                        print(
                            f"[HYBRID GUARANTEE OK] strict win on {n_strict}/{len(delta)} "
                            f"countries; {n_tie} ties. Mean ΔMIS = {delta.mean():+.4f}."
                        )
